# Generated by Django 5.2.5 on 2025-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=3)),
                ('documento', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=5)),
                ('poliza', models.CharField(max_length=10)),
                ('periodo', models.CharField(max_length=1)),
                ('valor_asegurado', models.CharField(max_length=21)),
                ('valor_prima', models.CharField(max_length=22)),
                ('doc_cobro', models.CharField(max_length=14)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('dias', models.CharField(max_length=5)),
                ('telefono_1', models.CharField(max_length=15)),
                ('telefono_2', models.CharField(max_length=15)),
                ('telefono_3', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=22)),
                ('departamento', models.CharField(max_length=22)),
                ('fecha_venta', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.CharField(max_length=10)),
                ('tipo_trans', models.CharField(max_length=3)),
                ('beneficiarios', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=1)),
                ('sucursal', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=10, null=True)),
                ('ultimos_digitos_cuenta', models.CharField(max_length=7)),
                ('entidad_bancaria', models.CharField(max_length=40)),
                ('nombre_banco', models.CharField(max_length=15)),
                ('estado_debito', models.CharField(max_length=15)),
                ('causal_rechazo', models.CharField(max_length=5)),
                ('codigo_canal', models.CharField(max_length=3)),
                ('descripcion_canal', models.CharField(max_length=15)),
                ('codigo_estrategia', models.CharField(max_length=15)),
                ('tipo_estrategia', models.CharField(max_length=50)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('fecha_entrega_colmena', models.DateField()),
                ('mes_a_trabajar', models.CharField(max_length=2)),
                ('id_custom', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_db', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=1, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=1, null=True)),
                ('texto', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.CharField(blank=True, max_length=1, null=True)),
                ('fisica', models.CharField(blank=True, max_length=1, null=True)),
                ('mejor_canal', models.CharField(blank=True, max_length=20, null=True)),
                ('contactar_al', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Importación de Datos',
                'verbose_name_plural': 'Importaciones de Datos',
                'db_table': 'data_import',
            },
        ),
    ]
