# Generated by Django 5.2.5 on 2025-08-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataimport',
            options={},
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='nombre_banco',
            field=models.CharField(max_length=40),
        ),
    ]
