# Generated by Django 5.2.5 on 2025-08-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_alter_dataimport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='causal_rechazo',
            field=models.CharField(max_length=200),
        ),
    ]
